### ISSUE TITLE
[Feature Request]: Add Tags to each group of AntiBlocks

### ISSUE THREAD

**Issue by TheBedrockMaster** [manmaed/AntiBlocksReChiseled#12]
### Feature Description

Add tags to each group of AntiBlocks, for example, have all the normal antiblocks have a tag (`antiblocksrechiseled:antiblocks`) and all the bright antiblocks have a tag (`antiblocksrechiseled:bright_antiblocks`), etc.

I don't want to manually add EMC to them all in 9sky 🤣

**Comment by manmaed** [comment]
if i remember correctly most EMC mods that i have played with use the recipes to get the enc values?

**Comment by manmaed** [comment]
added tags: 
antiblock_without_borders > contains all antiblocks with no borders
antiblock_with_borders   > contains all antiblocks with borders
antiblock_bright_colors  > contains all bright colored antiblocks
antiblock_wool_colors > contains all wool colored antiblocks

**Comment by manmaed** [comment]
now in forge, fabric neo 1.21.x

**Comment by TheBedrockMaster** [comment]
Any chance of getting this is 1.20.1 so I can use them for 9sky? Thanks btw.

**Comment by manmaed** [comment]
if you are using neo it has been taged 1.21.1

**Comment by TheBedrockMaster** [comment]
No, Forge 1.20.1.

**Comment by manmaed** [comment]
just tested 10.3 on forge 52.0.6 it it seems to work so have taged forge with 1.21.1 as well

**Comment by TheBedrockMaster** [comment]
All The Mods 9 To the sky is a 1.20(.1) pack, I'm wondering if you could please back support this feature to 1.20.1, I understand if you don't want to.

**Comment by manmaed** [comment]
all of the 1.20.x forge versions should be out

**Comment by TheBedrockMaster** [comment]
Thank you so much! 💖

**Comment by TheBedrockMaster** [comment]
Would it be possible to get these as item tags too?

**Comment by manmaed** [comment]
Done!

**Comment by TheBedrockMaster** [comment]
Awesome!

**Comment by manmaed** [comment]
the only item tag that don't exist is for pressure plates (there is one for wooden ones)
