### ISSUE TITLE
[Bug]: 0.4.4 incompatible with neoforge

### ISSUE THREAD

**Issue by mxnmnm** [manmaed/AntiBlocksReChiseled#13]
### AntiBlocksReChiseled version

0.4.4

### Minecraft Version

1.20.1

### Forge, Fabric or Neo?

Neo

### Forge/Fabric/Neo Version

Neo (47.1.106)

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

0.4.4 is incompatible with neoforge due to the different version numbering system it uses compared to forge

### Steps to reproduce

Install neoforge and antiblocksrechiseled 0.4.4 and crash

### Expected behaviour

no crash

### Log files

https://gist.github.com/mxnmnm/89abdaa21e1f66315cb77e08e3fb9bdd

### Additional information

You need to keep neo's different numbering system in mind when restricting forge versions

### Information

- [X] I have provided as much information as possible

**Comment by manmaed** [comment]
this was tagged as a forge mod-loader and i cant seem to get neoforge working this far down

**Comment by manmaed** [comment]
it seems that the last forge/neo is 47.1.3 so will downgrde and release neo taged jar

**Comment by manmaed** [comment]
https://www.curseforge.com/minecraft/mc-mods/antiblocksrechiseled/files/5644949 this file should work

**Comment by mxnmnm** [comment]
Is this the same as 0.4.4 with neoforge working? I got it to work by just changing the mods.toml restrictions in the jar lol

**Comment by manmaed** [comment]
yes
