### ISSUE TITLE
3rd party downloads are disabled on CurseForge

### ISSUE THREAD

**Issue by Su5eD** [manmaed/AntiBlocksReChiseled#4]
### Feature Description

Please consider enabling 3rd party downloads on CurseForge to allow the mod to be used in free and open source launchers, such as [Prism](https://prismlauncher.org/) or [MultiMC](https://multimc.org/).

**Comment by manmaed** [comment]
Thank you for your suggestion to enable 3rd party downloads for the mod on CurseForge. While we appreciate your interest in using our mod with free and open source launchers, such as Prism or MultiMC, we have decided not to allow 3rd party downloads at this time. Our policy is based on various factors, and we believe that it is the best approach for our mod and our users. We appreciate your feedback and hope that you will continue to enjoy using our mod on CurseForge.
