### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KurageAkagami** [manmaed/AntiBlocksReChiseled#5]
### AntiBlocksReChiseled version

v0.1.7

### Minecraft Version

1.19.2

### Forge Version Or Fabric Version

Forge(43.2.6)

### Modpack & Version

ATM8 v1.0.15

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Blocks not glowing after enabling them in shader settings

### Steps to reproduce

open "block.properties" from complementary reimagined shaders. 
Add the Anti block names after "block.10640=redstone_lamp:lit=true" with a space in between.

antiblocksrechiseled:wool_white => Is the only one that works

antiblocksrechiseled:wool_light_blue => For example doesn't work

### Expected behaviour

Blocks should glow

### Screenshots

![2023-04-26_17 35 56](https://user-images.githubusercontent.com/130392115/234627428-c499a11e-e214-48bd-8600-72ac75c2c62e.png)
![Screenshot 2023-04-26 173355](https://user-images.githubusercontent.com/130392115/234626841-cffecb7b-9f4f-4470-bb88-ec8447dcd0f7.png)

### Additional information

I added all the blocks into the block.properties file but only the white wool block emits light like intended. See attached screenshot

I would be glad if you could help me with that. I'm not sure if it is the shaderpack or the mod not handling it correctly because it works for other blocks as well just not for the anti blocks.

### Information

- [X] I have provided as much information as possible

**Comment by 5ully** [comment]
What other rendering based mods do you have installed?

**Comment by KurageAkagami** [comment]
just standard ATM8. I don't know all the rendering mods out of my head
except the forge sodium port and oculus.

**Comment by manmaed** [comment]
i have asked on the Shaders discord and was told
> this is just how IPBR works
