### ISSUE TITLE
[Feature Request]: Other old chisel blocks?

### ISSUE THREAD

**Issue by Thspooks** [manmaed/AntiBlocksReChiseled#7]
### Feature Description

Sorry if this kind of feature request posts arent allowed :"D They say curiosity killed the cat after all...
Its amazing to see someone that added back anti blocks, some of old chisel blocks are amazing. So heres my question: Do you have any plans on doing the same with other old chisel blocks (Science blocks ? :<) ? I dont wanna sound like the beggar types, im just curious thats all :D

**Comment by manmaed** [comment]
This mod was made only for the Anti Blocks

**Comment by 5ully** [comment]
Skill issue @manmaed
