### ISSUE TITLE
[Feature Request]: Use Athena or Fusion in place of CTM for connected textures in 1.19.3 onwards

### ISSUE THREAD

**Issue by ambientNexus** [manmaed/AntiBlocksReChiseled#9]
### Feature Description

Both mods are widely-used replacements for CTM.
Athena: https://modrinth.com/mod/athena-ctm
Fusion: https://modrinth.com/mod/fusion-connected-textures

**Comment by manmaed** [comment]
athena did this: ![](https://ss.manmaed.net/2023-09-01_00.51.37.png)
as for fusion its looking good: ![](https://ss.manmaed.net/1717542467.png)

**Comment by ambientNexus** [comment]
Well, that was an easy implementation. Next update will include fusion compatibility then, I assume?

**Comment by manmaed** [comment]
should be

**Comment by ambientNexus** [comment]
Perfect, thanks.

**Comment by manmaed** [comment]
will deploy 1.20.4 Neo/Forge/Fabric updates tomorrow

**Comment by ambientNexus** [comment]
Could you backport the changes you've made to the 1.20.1 versions as well? I'd prefer to be able to use it in tandem with other mods, and most mods don't work across 1.20.x versions due to the backend changes Mojang made between minor versions.

**Comment by manmaed** [comment]
1.20.1+ Should be online now
